name: Process Attachments

on:
  workflow_dispatch:
    inputs:
      situation_id:
        description: 'Situation ID'
        required: true
        type: string
      po_amount:
        description: 'PO Amount'
        required: false
        type: string
        default: "0"
      email:
        description: 'User Email'
        required: true
        type: string
      attachments:
        description: 'Attachments'
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Save attachments and run script
      id: run_script
      run: |
        mkdir -p data
        echo '${{ github.event.inputs.attachments }}' | jq -r '.[] | .name' | while read name; do touch data/$name; done
        python process_attachments.py data ${{ github.event.inputs.situation_id }} ${{ github.event.inputs.po_amount }}

    - name: Set output
      id: set_output
      run: |
        echo "::set-output name=status::$(cat status.txt)"
        echo "::set-output name=missing_attachments::$(cat missing_attachments.txt)"
