name: Process Attachments

on:
  workflow_dispatch:
    inputs:
      situation_id:
        description: 'Situation ID'
        required: true
        type: integer
      po_amount:
        description: 'PO Amount'
        required: false
        type: integer
        default: 0
      email:
        description: 'User Email'
        required: true
        type: string
      attachments:
        description: 'Attachments'
        required: true
        type: json

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sendgrid

    - name: Run script
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python process_attachments.py <<EOF
        {
          "situation_id": ${{ github.event.inputs.situation_id }},
          "po_amount": ${{ github.event.inputs.po_amount }},
          "email": "${{ github.event.inputs.email }}",
          "attachments": ${{ github.event.inputs.attachments }}
        }
        EOF
